FROM node:12.18.2-alpine as builder

WORKDIR /app

COPY package.json .
COPY yarn.lock .
COPY tsconfig.json .

RUN yarn install --production

FROM node:12.18.2-alpine
COPY --from=builder /app/node_modules /app/node_modules

COPY . .

EXPOSE 3000
CMD [ "yarn", "dev" ]