version: "3.4"
services:
  api:
    build:
      context: "./backend"
      dockerfile: "Dockerfile.dev"
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app/go

  front:
    build:
      context: "./frontend"
      target: base
    command: "yarn dev"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/js/base
      - ./frontend/node_modules:/app/js/base/node_modules
