version: "3.4"
services:
  api:
    build:
      context: "./backend"
      target: base
    command: "air -c .air.toml"
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app/go/base
    env_file:
      - ./backend/server.env

  front:
    build:
      context: "./frontend"
      target: base
    command: "yarn dev"
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app/js/base
      - ./frontend/node_modules:/app/js/base/node_modules
